<<: !include "../hpack/lorentz/module.yaml"

<<: *meta
name:                stkr-token
version:             0.1.0.0

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: TODO

dependencies:
  - base-noprelude >= 4.7 && < 5
  - morley
  - morley-prelude
  - named
  - hex-text

library:
  <<: *lorentz-lib-common

  dependencies:
    - containers
    - data-default
    - morley
    - morley-prelude
    # deps for tztest
    - aeson
    - bytestring
    - haskeline
    - cryptonite
    - text
    - process
    - singletons
    - fmt
    - microlens
    - time
    - yaml
    - vinyl

  when:
    - condition: os(windows)
      then:
        extra-libraries: sodium
      else:
        pkg-config-dependencies: libsodium

executables:
  stkr-token-cli:
    <<: *exec-common

    dependencies:
      - aeson
      - yaml
      - base-noprelude >= 4.7 && < 5
      - base16-bytestring
      - containers
      - fmt
      - stkr-token
      - morley
      - morley-prelude
      - optparse-applicative
      - turtle
      - text
    ghc-options:
      - -threaded # IMPORTANT!

  stkr-token-test-end2end:
    <<: *lorentz-default-extensions
    main: Main.hs
    source-dirs: test-end2end

    dependencies:
      - aeson
      - base-noprelude >= 4.7 && < 5
      - containers
      - hspec
      - hspec-expectations
      - stkr-token
      - morley
      - morley-prelude
      - tasty
      - tasty-hspec
      - text
      - fmt
      - time
      - yaml


tests:
  stkr-token-test:
    <<: *test-common

    dependencies:
      - base-noprelude >= 4.7 && < 5
      - containers
      - fmt
      - HUnit
      - hspec
      - hspec-expectations
      - stkr-token
      - morley
      - morley-prelude
      - lorentz-contracts
      - microlens
      - QuickCheck
      - tasty
      - tasty-hspec
      - time
      - vinyl
