# When you update resolver or extra-deps you might need to update
# haskell.nix version to make sure it contains the latest hackage
# and stackage indexes
resolver: lts-14.15

extra-deps:
# morley
- git: https://gitlab.com/morley-framework/morley.git
  commit: 13a60544b67bf5d168840ea7ab6ac75ea89a069a
  subdirs:
  - code/morley
  - code/morley-prelude
  - code/lorentz

# required for morley
- aeson-options-0.1.0
- base58-bytestring-0.1.0
- constraints-0.11
- hex-text-0.1.0.0
- pretty-terminal-0.1.0.0
- show-type-0.1.1
- tasty-hunit-compat-0.2

# optional nix support (for `stack --nix`)
nix:
  pure: false
  packages: [ pkg-config libsodium zlib]
