steps:
 - label: check trailing whitespace
   command: .buildkite/check-trailing-whitespace.sh

 - label: build
   commands: nix-build -A all-components

 - label: test
   commands: nix-build -A run-test

 - label: end2end
   command: nix-build end2end.nix --arg useTezosDerivation true && ./result
   branches: "master"
